name: Deploy NextJs to S3 bucket

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: [self-hosted, orangepi]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup NodeJs
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install ALL Dependencies
        run: npm ci

      - name: Security Audit
        # This will check for known vulnerabilities
        # Use '--audit-level=high' to only fail on serious issues
        run: npm audit --audit-level=high

      - name: Build NextJs
        run: npm run build

      - name: Prune Development Dependencies
        run: npm prune --production

      - name: Configure AWS Credentials
        if: github.event_name == 'push'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy to S3
        if: github.event_name == 'push'
        run: |
          aws s3 sync out/ s3://ucapistran-blog --delete
